-   id: prettier-standard
    name: prettier-standard
    description: 'prettier and standard brought together'
    entry: prettier-standard
    language: node
    files: \.js$
-   id: black
    name: black
    description: 'Black: The uncompromising Python code formatter'
    entry: black
    language: python
    language_version: python3
    require_serial: true
    types: [python]
