-   id: prettier-standard
    name: prettier-standard
    description: 'prettier and standard brought together'
    entry: prettier-standard
    language: node
    files: \.js$
    exclude: ^build/
-   id: black
    name: black
    description: 'Black: The uncompromising Python code formatter'
    entry: black
    language: python
    language_version: python3
    require_serial: true
    types: [python]
    exclude: ^migrations/
-   id: flake8
    name: flake8
    description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
    entry: flake8
    language: python
    types: [python]
    exclude: ^migrations/
    require_serial: true
-   id: isort
    name: isort
    description: 'A Python utility / library to sort imports.'
    entry: isort
    language: python
    types: [python]
    exclude: ^migrations/
